name: CI

on: [push, repository_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macOS-latest, windows-latest]
        include:
        - os: macOS-latest
          TARGET: x86_64-apple-darwin
        - os: windows-latest
          TARGET: x86_64-pc-windows-msvc
        - os: ubuntu-latest
          TARGET: x86_64-unknown-linux-musl
    runs-on: ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup toolchain
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            override: true
            target: ${{matrix.TARGET}}
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: rust-cargo
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
      - name: py-deps
        run: |
          pip install --upgrade pip
          pip install cffi maturin
      - name: py-install
        run: |
          maturin build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
            name: wheel
            path: target/wheels
        

